name: workflow_for_5

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt-openjdk'
    
    - name: Build and Test with Maven
      run: mvn clean verify --file pom.xml
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        upload-token: ${{ secrets.CODECOV_TOKEN }}
